spring:
  jackson:
    default-property-inclusion: non-empty
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true